[package]
name = "iptool-core"
version = "1.0.0"
authors = ["timmonfette1 <monfette.timothy@gmail.com>"]
repository = "https://github.com/timmonfette1/iptool-core"
license = "MIT"
description = "Rust core of the IP Tool"

[dependencies]
regex = "0.2"
